---
- name: Crear directorio de la aplicación
  file:
    path: /home/webapp/app
    state: directory
    owner: webapp
    group: webapp

- name: Crear package.json
  template:
    src: package.json.j2
    dest: /home/webapp/app/package.json
    owner: webapp
    group: webapp

- name: Crear aplicación Node.js
  template:
    src: app.js.j2
    dest: /home/webapp/app/app.js
    owner: webapp
    group: webapp

- name: Instalar dependencias npm
  npm:
    path: /home/webapp/app
  become_user: webapp

- name: Crear servicio systemd
  template:
    src: webapp.service.j2
    dest: /etc/systemd/system/webapp.service
  notify: 
    - reload systemd
    - restart webapp

- name: Iniciar y habilitar servicio webapp
  service:
    name: webapp
    state: started
    enabled: yes
