---
- hosts: all
  become: yes
  tasks:
    - name: Instalar nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    
    - name: Crear página simple
      copy:
        content: "<h1>SYP-DEV ANSIBLE + VAGRANT</h1>"
        dest: /var/www/html/index.html
    
    - name: Iniciar nginx
      service:
        name: nginx
        state: started
