Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    
    # Primera máquina
    config.vm.define "vm1" do |vm1|
        vm1.vm.network "forwarded_port", guest: 80, host: 8080
        vm1.vm.network "private_network", ip: "192.168.56.10"
        vm1.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.name = "Ubuntu-VM1"
        end
    end
    
    # Segunda máquina
    config.vm.define "vm2" do |vm2|
        vm2.vm.network "forwarded_port", guest: 80, host: 8081
        vm2.vm.network "private_network", ip: "192.168.56.11"
        vm2.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.name = "Ubuntu-VM2"
        end
    end
end