---
- name: Instalar Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Iniciar Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Crear página simple
  copy:
    content: "<h1>Ansible con roles</h1>"
    dest: /var/www/html/index.html

- name: Configurar permisos del archivo
  file:
    path: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'