Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.galaxy_role_file = "requirements.yaml"
    ansible.galaxy_roles_path = "roles"
    ansible.galaxy_command = "ansible-galaxy install -r %{role_file} --roles-path %{roles_path}"
    ansible.become = true
    ansible.become_user = "root"
    ansible.verbose = "v"
    ansible.compatibility_mode = "2.0"
  end
end
