Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  # Instalar Ansible en la VM y ejecutar el playbook
  config.vm.provision "shell", inline: <<-SHELL
    # Instalar Ansible
    apt-get update
    apt-get install -y software-properties-common
    add-apt-repository --yes --update ppa:ansible/ansible
    apt-get install -y ansible
    
    # Ejecutar el playbook
    cd /vagrant
    ansible-playbook -i "localhost," -c local playbook.yml
  SHELL
end
