Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "private_network", ip: "192.168.56.10"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "Vagrant-VM"
    end
    
    config.vm.provision "shell", inline: <<-SHELL
        echo "Hola desde Vagrant Provision!"
        mkdir -p /home/vagrant/directorio_ejemplo
    SHELL
end
