---
- hosts: all
  become: yes
  tasks:
    - name: Instalar nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    
    - name: Crear página simple
      copy:
        content: "<h1>SYP-DEV ANSIBLE + VAGRANT</h1>"
        dest: /var/www/html/index.html
    
    - name: Iniciar nginx
      service:
        name: nginx
        state: started


- hosts: all
  become: yes
  tasks:
    - name: Actualizar caché de apt
      apt:
        update_cache: yes

    - name: Instalar MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Recoger información de servicios
      service_facts:

    - name: Iniciar MySQL si existe
      service:
        name: mysql
        state: started
        enabled: yes
      when: "'mysql.service' in ansible_facts.services"

